
#define STM32F4xx

//#define STM32F407xx

#define STM32F4_DISCOVERY

//#define HAL_SPI_MODULE_ENABLED

#define DMA2_STREAM3_DISABLE_IRQHANDLER

#define DMA2_STREAM6_DISABLE_IRQHANDLER

#define FATFS_SDIO_4BIT   0

